<?php

namespace CatMS\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentFieldsRepository extends EntityRepository
{
}
