parameters:
#    cat_ms_frontend.example.class: CatMS\FrontendBundle\Example

services:
#    cat_ms_frontend.example:
#        class: %cat_ms_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
